services:
  db:
    platform: linux/arm64
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: admin
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432"

  backend:
    platform: linux/arm64
    image: ditod/compl-notes-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      - db
    environment:
      SPRING_DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATABASE_USER: admin
      SPRING_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      VIRTUAL_HOST: ${VIRTUAL_HOST}

  frontend:
    platform: linux/arm64
    image: ditod/compl-notes-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://${VIRTUAL_HOST}/api
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    depends_on:
      - backend
    ports:
      - "80"
      - "443"

networks:
  default:
    external: true
    name: nginx_notes



