/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/users/{username}/notes/{noteId}": {
    get: operations["getNote"];
    put: operations["updateNote"];
    delete: operations["deleteNote"];
  };
  "/users/{username}/notes": {
    get: operations["allNotes"];
    post: operations["createNote"];
  };
  "/auth/signup": {
    post: operations["signup"];
  };
  "/auth/logout": {
    post: operations["logout"];
  };
  "/auth/login": {
    post: operations["login"];
  };
  "/users": {
    get: operations["listUsers"];
  };
  "/users/{username}": {
    get: operations["getUser"];
  };
  "/user-images/{imageId}": {
    get: operations["getUserImage"];
  };
  "/note-images/{imageId}": {
    get: operations["getNoteImage"];
  };
  "/auth/user": {
    get: operations["getAuthUser"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    NoteImageRequest: {
      /** Format: uuid */
      id?: string;
      altText?: string;
      /** Format: binary */
      file?: string;
    };
    NoteRequest: {
      title: string;
      content: string;
      images?: components["schemas"]["NoteImageRequest"][];
    };
    Note: {
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: uuid */
      id?: string;
      title?: string;
      content: string;
      owner: components["schemas"]["User"];
      images: components["schemas"]["NoteImage"][];
    };
    NoteImage: {
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: uuid */
      id: string;
      altText?: string;
      note: components["schemas"]["Note"];
    };
    Permission: {
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: uuid */
      id?: string;
      action: string;
      entity: string;
      access: string;
      description: string;
      roles?: components["schemas"]["Role"][];
      authority?: string;
    };
    Role: {
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: uuid */
      id?: string;
      name: string;
      description: string;
      users: components["schemas"]["User"][];
      permissions: components["schemas"]["Permission"][];
    };
    User: {
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: uuid */
      id?: string;
      email: string;
      username: string;
      name?: string;
      notes: components["schemas"]["Note"][];
      image?: components["schemas"]["UserImage"];
      roles: components["schemas"]["Role"][];
    };
    UserImage: {
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: uuid */
      id?: string;
      altText?: string;
      contentType: string;
      blob: string[];
      user: components["schemas"]["User"];
    };
    SignupRequest: {
      username: string;
      name: string;
      email: string;
      password: string;
      confirmPassword: string;
      agreeToTermsOfServiceAndPrivacyPolicy?: boolean;
      passwordsMatch?: boolean;
    };
    AuthUserDto: {
      roles?: components["schemas"]["RoleSummary"][];
      name?: string;
      /** Format: uuid */
      id: string;
      username: string;
      image?: components["schemas"]["UserImageSummary"];
    };
    AuthUserResponse: {
      user?: components["schemas"]["AuthUserDto"];
    };
    PermissionSummary: {
      access?: string;
      action?: string;
      entity?: string;
    };
    RoleSummary: {
      name?: string;
      permissions?: components["schemas"]["PermissionSummary"][];
    };
    UserImageSummary: {
      /** Format: uuid */
      id: string;
    };
    LoginRequest: {
      username: string;
      password: string;
      remember?: boolean;
    };
    UserFilteredResponse: {
      name?: string;
      /** Format: uuid */
      id: string;
      username: string;
      /** Format: uuid */
      imageId?: string;
    };
    UserSummaryResponse: {
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      name?: string;
      /** Format: uuid */
      id: string;
      username: string;
      image?: components["schemas"]["UserImageSummary"];
    };
    NoteSummary: {
      title: string;
      /** Format: uuid */
      id: string;
    };
    UserNotesResponse: {
      notes: components["schemas"]["NoteSummary"][];
      name?: string;
      /** Format: uuid */
      id: string;
      username: string;
      image?: components["schemas"]["UserImageSummary"];
    };
    NoteSummaryResponse: {
      title: string;
      /** Format: uuid */
      id: string;
      content: string;
      owner: components["schemas"]["OwnerSummary"];
      images: components["schemas"]["NoteImage"][];
      /** Format: date-time */
      updatedAt: string;
    };
    OwnerSummary: {
      /** Format: uuid */
      id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  getNote: {
    parameters: {
      path: {
        noteId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["NoteSummaryResponse"];
        };
      };
    };
  };
  updateNote: {
    parameters: {
      query: {
        newNote: components["schemas"]["NoteRequest"];
      };
      path: {
        username: string;
        noteId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Note"];
        };
      };
    };
  };
  deleteNote: {
    parameters: {
      path: {
        username: string;
        noteId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  allNotes: {
    parameters: {
      path: {
        username: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserNotesResponse"];
        };
      };
    };
  };
  createNote: {
    parameters: {
      query: {
        note: components["schemas"]["NoteRequest"];
      };
      path: {
        username: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Note"];
        };
      };
    };
  };
  signup: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AuthUserResponse"];
        };
      };
    };
  };
  logout: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AuthUserResponse"];
        };
      };
    };
  };
  listUsers: {
    parameters: {
      query?: {
        filter?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserFilteredResponse"][];
        };
      };
    };
  };
  getUser: {
    parameters: {
      path: {
        username: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserSummaryResponse"];
        };
      };
    };
  };
  getUserImage: {
    parameters: {
      path: {
        imageId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": string[];
        };
      };
    };
  };
  getNoteImage: {
    parameters: {
      path: {
        imageId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": string[];
        };
      };
    };
  };
  getAuthUser: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AuthUserResponse"];
        };
      };
    };
  };
}
