services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: notes
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5432:5432"

#  redis:
#    image: redis
#    container_name: redis
#    ports:
#      - "6379:6379"
